# Generated by Django 6.0.2 on 2026-02-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('tipo', models.CharField(choices=[('GERAL', 'Ensino Geral (C.E.J / C.F.B)'), ('TECNICO', 'Ensino Técnico Profissional')], max_length=10, verbose_name='Tipo de Ensino')),
                ('tem_prova_semestral', models.BooleanField(default=False, verbose_name='Tem Prova Semestral?')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='escola.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde')], max_length=1)),
                ('ano_letivo', models.IntegerField(default=2026)),
                ('vagas', models.PositiveIntegerField(default=45)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
            ],
        ),
    ]
