# Generated by Django 6.0.2 on 2026-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='classe',
            field=models.CharField(choices=[('INI', 'Iniciação'), ('1', '1ª Classe'), ('2', '2ª Classe'), ('3', '3ª Classe'), ('4', '4ª Classe'), ('5', '5ª Classe'), ('6', '6ª Classe'), ('7', '7ª Classe'), ('8', '8ª Classe'), ('9', '9ª Classe'), ('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], default='10', max_length=3),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('PRIMARIO', 'Ensino Primário'), ('I_CICLO', 'I Ciclo do Ensino Secundário'), ('GERAL', 'Ensino Geral (II Ciclo)'), ('TECNICO', 'Ensino Técnico-Profissional')], max_length=10, verbose_name='Tipo de Ensino'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
