# Generated by Django 6.0.2 on 2026-02-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('PRIMARIO', 'Ensino Primário'), ('I_CICLO', 'I Ciclo'), ('GERAL', 'Ensino Geral (II Ciclo)'), ('TECNICO', 'Ensino Técnico-Profissional')], max_length=10, verbose_name='Tipo de Ensino'),
        ),
    ]
