# Generated by Django 6.0.2 on 2026-03-21 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='cursos',
            field=models.ManyToManyField(related_name='disciplinas', to='escola.curso'),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas_habilitadas',
            field=models.ManyToManyField(related_name='professores_habilitados', to='escola.disciplina'),
        ),
        migrations.CreateModel(
            name='Atribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_atribuicoes', to='escola.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_curricular', to='escola.turma')),
            ],
            options={
                'verbose_name': 'Atribuição de Aula',
                'verbose_name_plural': 'Atribuições de Aulas',
                'unique_together': {('disciplina', 'turma')},
            },
        ),
    ]
