# Generated by Django 6.0.2 on 2026-03-22 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_remove_disciplina_curso_remove_professor_disciplinas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='cursos',
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('INI', 'Iniciação'), ('1', '1ª Classe'), ('2', '2ª Classe'), ('3', '3ª Classe'), ('4', '4ª Classe'), ('5', '5ª Classe'), ('6', '6ª Classe'), ('7', '7ª Classe'), ('8', '8ª Classe'), ('9', '9ª Classe'), ('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], max_length=3)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='escola.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
            ],
            options={
                'verbose_name': 'Grade Curricular',
                'verbose_name_plural': 'Grades Curriculares',
                'unique_together': {('curso', 'disciplina', 'classe')},
            },
        ),
    ]
