# Generated by Django 6.0.2 on 2026-02-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0003_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('bi_numero', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('classe_pretendida', models.CharField(choices=[('INI', 'Iniciação'), ('1', '1ª Classe'), ('2', '2ª Classe'), ('3', '3ª Classe'), ('4', '4ª Classe'), ('5', '5ª Classe'), ('6', '6ª Classe'), ('7', '7ª Classe'), ('8', '8ª Classe'), ('9', '9ª Classe'), ('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], max_length=3)),
                ('foto_tipo_passe', models.ImageField(upload_to='inscricoes/fotos/')),
                ('bi_frente', models.ImageField(upload_to='inscricoes/documentos/')),
                ('bi_verso', models.ImageField(upload_to='inscricoes/documentos/')),
                ('certificado_anterior', models.FileField(upload_to='inscricoes/documentos/')),
                ('comprovativo_pagamento', models.FileField(upload_to='inscricoes/pagamentos/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('observacoes_adm', models.TextField(blank=True, help_text='Motivo de rejeição, por exemplo.', null=True)),
                ('curso_pretendido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escola.curso')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
