# Generated by Django 6.0.2 on 2026-02-23 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('escola', '0003_disciplina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='bi_frente',
            field=models.ImageField(upload_to='tarimba/inscricoes/documentos/', verbose_name='B.I. Frente'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='bi_numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número do B.I.'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='bi_verso',
            field=models.ImageField(upload_to='tarimba/inscricoes/documentos/', verbose_name='B.I. Verso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='certificado_anterior',
            field=models.FileField(upload_to='tarimba/inscricoes/documentos/', verbose_name='Certificado de Habilitações'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='classe_pretendida',
            field=models.CharField(choices=[('INI', 'Iniciação'), ('1', '1ª Classe'), ('2', '2ª Classe'), ('3', '3ª Classe'), ('4', '4ª Classe'), ('5', '5ª Classe'), ('6', '6ª Classe'), ('7', '7ª Classe'), ('8', '8ª Classe'), ('9', '9ª Classe'), ('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], max_length=3, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='comprovativo_pagamento',
            field=models.ImageField(upload_to='tarimba/inscricoes/pagamentos/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='curso_pretendido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escola.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='foto_tipo_passe',
            field=models.ImageField(upload_to='tarimba/inscricoes/fotos/', verbose_name='Foto Tipo Passe'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='observacoes_adm',
            field=models.TextField(blank=True, help_text='Ex: Documento ilegível', null=True, verbose_name='Observações do Administrador'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone / WhatsApp'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=20, unique=True, verbose_name='Nº de Processo')),
                ('esta_congelado', models.BooleanField(default=False, verbose_name='Matrícula Congelada')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='escola.turma')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')])),
                ('mac', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='MAC (Média Avaliação Contínua)')),
                ('npp', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='NPP (Prova Parcial)')),
                ('npt', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='NPT (Prova Trimestral)')),
                ('exame', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Exame/Recurso')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('esta_presente', models.BooleanField(default=True, verbose_name='Presente')),
                ('justificada', models.BooleanField(default=False, verbose_name='Falta Justificada')),
                ('documento_justificativo', models.FileField(blank=True, null=True, upload_to='tarimba/justificativas/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='academico.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
            ],
        ),
    ]
