# Generated by Django 6.0.2 on 2026-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_inscricao_bi_frente_alter_inscricao_bi_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='observacoes_adm',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='mac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='npp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='NPP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='npt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='NPT'),
        ),
    ]
