# Generated by Django 6.0.2 on 2026-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_aluno_options_alter_inscricao_observacoes_adm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='observacao_justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Nota do Aluno'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(),
        ),
    ]
