# Generated by Django 6.0.2 on 2026-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_presenca_observacao_justificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='comprovativo_pagamento',
            field=models.ImageField(blank=True, null=True, upload_to='tarimba/inscricoes/pagamentos/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Revisão)'), ('CONFIRMADO', 'Confirmado (Aguardando Pagamento)'), ('PAGO', 'Pago (Matrícula Concluída)'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
    ]
