# Generated by Django 6.0.2 on 2026-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_inscricao_comprovativo_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero_processo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
