# Generated by Django 6.0.2 on 2026-04-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_aluno_numero_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
    ]
