# Generated by Django 6.0.2 on 2026-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_alter_inscricao_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoriosDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relatórios e Estatísticas',
                'verbose_name_plural': '📊 Ver Relatórios e Estatísticas',
                'managed': False,
            },
        ),
    ]
