# Generated by Django 6.0.2 on 2026-04-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_relatoriosdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatoriosdashboard',
            options={'managed': False, 'verbose_name_plural': '📊 Ver Relatórios e Estatísticas'},
        ),
    ]
