# Generated by Django 6.0.5 on 2026-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_inscricao_status_confirmado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero_processo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nº de Processo'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='comprovativo_pagamento',
            field=models.ImageField(upload_to='tarimba/inscricoes/pagamentos/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
