# Generated by Django 6.0.5 on 2026-05-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_aluno_numero_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='comprovativo_pagamento',
            field=models.ImageField(blank=True, null=True, upload_to='tarimba/inscricoes/pagamentos/', verbose_name='Comprovativo de Pagamento'),
        ),
    ]
