# Generated by Django 6.0.5 on 2026-06-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_confirmacaomatricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaomatricula',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='confirmacaomatricula',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='academico.aluno', verbose_name='Aluno'),
        ),
    ]
