# Generated by Django 6.0.2 on 2026-06-06 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_confirmacaomatricula_nome_completo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True, verbose_name='Ano Lectivo')),
                ('atual', models.BooleanField(default=False, verbose_name='Ano Atual')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-ano'],
            },
        ),
    ]
